/*
 * Для выполнения этого упражнения вам придется просмотреть исходный код
 * класса j a v a . u t i l . S c a n n e r . Если при использовании класса S c a n n e r операция
 * ввода завершается неудачно, в этом классе перехватывается исключение в связи
 * с ошибками ввода данных и закрывается ресурс, из которого осуществляется
 *
 * ввод. Что произойдет, если ири закрытии ресурса будет сгенерировано исклю-
 * чение? Каким образом эта реализация взаимодействует с обработкой подавля-
 * емых исключений в операторе t r y с ресурсами?
 */

import java.util.Scanner;

public class Pr7 {
    public static void main(String[] args) {
        Scanner scanner;
//        find .close and lastException
    }
}
